cp ../../../../verification/tutorial_global_oce_latlon/input/bathymetry.bin ../input
cp ../../../../verification/tutorial_global_oce_latlon/input/lev_s.bin ../input
cp ../../../../verification/tutorial_global_oce_latlon/input/lev_s.bin ../input
cp ../../../../verification/tutorial_global_oce_latlon/input/lev_sss.bin ../input
cp ../../../../verification/tutorial_global_oce_latlon/input/lev_sst.bin ../input
cp ../../../../verification/tutorial_global_oce_latlon/input/lev_t.bin ../input
cp ../../../../verification/tutorial_global_oce_latlon/input/ncep_emp.bin ../input
cp ../../../../verification/tutorial_global_oce_latlon/input/ncep_qnet.bin ../input
cp ../../../../verification/tutorial_global_oce_latlon/input/trenberth_taux.bin ../input
cp ../../../../verification/tutorial_global_oce_latlon/input/trenberth_tauy.bin ../input
