#! /usr/bin/env bash

#- in order to save disc space, take files:
fileList="grid_cs32.face001.bin grid_cs32.face002.bin grid_cs32.face003.bin grid_cs32.face004.bin grid_cs32.face005.bin grid_cs32.face006.bin"

#- from this dir:
fromDir="../../tutorial_held_suarez_cs/input"

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

#- also, take most files
#- from this dir:
fromDir="../input"

fileList1=`( cd $fromDir ; echo *.bin )`
fileList2=`( cd $fromDir ; echo *data* )`
fileList3=`( cd $fromDir ; echo pickup* )`
fileList="$fileList1 $fileList2 $fileList3"

echo 'fileList=' $fileList

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
