#! /usr/bin/env bash

###########################################################################
# Link the bin files from the tutorial_global_oce_latlon experiment

fromDir="../../tutorial_global_oce_latlon/input"

fileList=`( cd $fromDir ; echo *.bin )`

if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

###########################################################################
# Link the input files from the input directory

fileList="data data.cal data.diagnostics data.exf data.gmredi eedata eedata.mth POLY3.COEFFS prof_exemple.nc"

fromDir="../input"

if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

###########################################################################
# Link the code files

fileList="CPP_OPTIONS.h DIAGNOSTICS_SIZE.h EXF_OPTIONS.h PROFILES_OPTIONS.h SIZE.h SIZE.h_mpi"

fromDir="../code"


if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx ../code_dv/$xx
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi