#! /usr/bin/env bash

###########################################################################
# Link the exch2 face files from the held_suarez experiment

fileList="grid_cs32.face001.bin grid_cs32.face002.bin grid_cs32.face003.bin grid_cs32.face004.bin grid_cs32.face005.bin grid_cs32.face006.bin"

fromDir="../../tutorial_held_suarez_cs/input"

if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

###########################################################################
# Link the input files from the seaice experiment

fileList="data data.cal data.exf data.gmredi data.pkg data.seaice eedata eedata.mth runoff_temperature.bin tr_checklist"

fromDir="../input.seaice"

if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

###########################################################################
# Link the input files from the base experiment

fileList="bathy_Hmin50.bin lev_S_cs_15k.bin lev_surfS_cs_12m.bin lev_surfT_cs_12m.bin lev_T_cs_15k.bin proj_cs32_2uEvN.bin regMask_lat24.bin shiEmPR_cs32.bin shiQnet_cs32.bin trenberth_taux.bin trenberth_tauy.bin"

fromDir="../input"

if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi



###########################################################################
# Link the *.bin and pickup* files from the icedyn experiment

fileList=`(cd ../input.icedyn ; ls -1 *.bin pickup*)`

fromDir="../input.icedyn"

if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

###########################################################################
# Link the code files

fileList="CPP_OPTIONS.h DIAG_OPTIONS.h DIAGNOSTICS_SIZE.h EXF_OPTIONS.h SEAICE_OPTIONS.h SIZE.h SIZE.h_mpi"

fromDir="../code"


if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx ../code_dv/$xx
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi