#! /usr/bin/env bash

###################################################
# Take the face files from the held_suarez tutorial

#- in order to save disc space, take files:
fileList="grid_cs32.face001.bin grid_cs32.face002.bin grid_cs32.face003.bin grid_cs32.face004.bin grid_cs32.face005.bin grid_cs32.face006.bin"

#- from this dir:
fromDir="../../tutorial_held_suarez_cs/input"

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

###################################################
# Take the bin files from the main input dir

#- in order to save disc space, take files:
fileList=`(cd ../input ; ls -1 *.bin ee*)`

#- from this dir:
fromDir="../input"

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

###################################################
# Take the bin and pickup files from the icedyn dir

#- in order to save disc space, take files:
fileList=`(cd ../input.icedyn ; ls -1 *.bin pickup*)`

#- from this dir:
fromDir="../input.icedyn"

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

###################################################
# Take the data files from the seaice dir

#- in order to save disc space, take files:
fileList="data.cal data.exf data.gmredi data.seaice runoff_temperature.bin"

#- from this dir:
fromDir="../input.seaice"

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

###################################################
# Take the compile files from the code dir

#- in order to save disc space, take files:
fileList="CPP_OPTIONS.h DIAG_OPTIONS.h DIAGNOSTICS_SIZE.h EXF_OPTIONS.h SEAICE_OPTIONS.h SIZE.h SIZE.h_mpi"

#- from this dir:
fromDir="../code"

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r ../code_dv/$xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx ../code_dv
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi